# Generated by Django 4.0 on 2022-04-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_products_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
