# Generated by Django 4.0 on 2022-04-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_products_discount_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
