# Generated by Django 4.0 on 2022-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_products_title_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
