# Generated by Django 4.0 on 2022-04-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_category_title_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
